config/routes.rb
Rails.application.routes.draw do

  resources :profile, only: [:show] do
    resources :user_tag, only: [:create]
  end

  get 'project_view/new'

  resources :project_files

  resources :project_image_attachments

  resources :projects do
    resources :project_likes, only: [:new]
    resources :project_comments, only: [:create]
    resources :project_tag, only: [:create]
  end

  devise_for :users

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :project_image_attachments, :dependent => :destroy
	has_many :project_files, :dependent => :destroy
	has_many :project_likes, :dependent => :destroy
	has_many :project_views, :dependent => :destroy
	has_many :project_comments, :dependent => :destroy
	has_many :project_tag_maps, :dependent => :destroy
	has_many :project_tags, :through => :project_tag_maps
	accepts_nested_attributes_for :project_image_attachments, :project_files

	after_initialize :set_defaults

	def likeProject user_id
    	if (!likedProject?(user_id))
	    	ProjectLike.create(:project_id => self.id, :user_id => user_id)
	    	self.updateLikes
	    end
	end

	def likedProject? user_id
		self.project_likes.pluck(:user_id).include?(user_id) || self.user_id == user_id
	end

	def viewProject user_id
		if (!viewedProject?(user_id)) # only counting unique views if I identify a user (i.e. if the user is logged in)
			if (user_id)
				ProjectView.create(:project_id => self.id, :user_id => user_id)
				self.updateViews(0)
			else
				# Should I count views where the user is not signed in?
				self.updateViews(1)
			end
		end
		self.views
	end

	def viewedProject? user_id
		if (user_id)
			self.project_views.pluck(:user_id).include?(user_id) || self.user_id == user_id
		else
			false
		end
	end

	def commentedProject? user_id
		if (user_id)
			self.project_comments.pluck(:user_id).include?(user_id) || self.user_id == user_id
		else
			true # You have to be logged in to be able to rate and comment
		end
	end

	def updateScore
		scores = self.project_comments.all.pluck(:score)
		scores.delete(0)
		if (scores.length > 0)
			self.update(:score => scores.sum.to_f / scores.length.to_f)
		end
	end

	def updateLikes
		self.update(:likes => self.project_likes.length)
	end

	def updateViews value
		self.update(:views => self.project_views.length + value)
	end

	private
	def set_defaults
		self.likes ||= 0;
		self.views ||= 0;
		self.score ||= 0;
	end
end

app/models/project_comment.rb
class ProjectComment < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
end

app/models/project_file.rb
class ProjectFile < ActiveRecord::Base
  mount_uploader :file, ProjectFileUploader
  belongs_to :project
end

app/models/project_image_attachment.rb
class ProjectImageAttachment < ActiveRecord::Base
	mount_uploader :projectimage, ProjectImageUploader
	belongs_to :project
end

app/models/project_like.rb
class ProjectLike < ActiveRecord::Base
	belongs_to :project
end

app/models/project_tag.rb
class ProjectTag < ActiveRecord::Base
	has_many :project_tag_maps
	has_many :projects, :through => :project_tag_maps
end

app/models/project_tag_map.rb
class ProjectTagMap < ActiveRecord::Base
	belongs_to :project_tag
	belongs_to :project
end

app/models/project_view.rb
class ProjectView < ActiveRecord::Base
	belongs_to :project
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
  has_many :project_likes
  has_many :project_views
  has_many :project_comments
  has_many :user_tag_maps
  has_many :user_tags, :through => :user_tag_maps
  mount_uploader :userimage, UserimageUploader

  def projects_scores
  	projects = self.projects
  	likes = 0
  	views = 0
  	score = 0.0
  	nr = projects.length
  	projects.each do |p|
  		if (p.score != 0)
  			score = score + p.score
  		else
  			nr -= 1
  		end
  		likes = likes + p.likes
  		views = views + p.views
  	end
    if (nr != 0)
  	   score = score / nr
    else
       score = 0.0
    end
  	[likes,views,score]
  end
  
end

app/models/user_tag.rb
class UserTag < ActiveRecord::Base
	has_many :user_tag_maps
	has_many :users, :through => :user_tag_maps
end

app/models/user_tag_map.rb
class UserTagMap < ActiveRecord::Base
	belongs_to :user
	belongs_to :user_tag
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@user = current_user
	end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  
  def show
  	@profile_user = User.find(params[:id])
  	@profile = current_user
    @user_tag = UserTag.new
  	@user = current_user
  	@projects = @profile_user.projects.order(:created_at).reverse_order
  	@user_tags = @profile_user.user_tags
  	if @projects.length > 3
  		@projects = @projects[0..2]
  	end
  end



  # to edit a user user edit_user_registration_path => http://localhost:3000/users/edit

end

app/controllers/project_image_attachments_controller.rb
class ProjectImageAttachmentsController < ApplicationController
  before_action :set_project_image_attachment, only: [:show, :edit, :update, :destroy]

  # GET /project_image_attachments
  # GET /project_image_attachments.json
  def index
    @project_image_attachments = ProjectImageAttachment.all
  end

  # GET /project_image_attachments/1
  # GET /project_image_attachments/1.json
  def show
  end

  # GET /project_image_attachments/new
  def new
    @project_image_attachment = ProjectImageAttachment.new
  end

  # GET /project_image_attachments/1/edit
  def edit
  end

  # POST /project_image_attachments
  # POST /project_image_attachments.json
  def create
    @project_image_attachment = ProjectImageAttachment.new(project_image_attachment_params)

    respond_to do |format|
      if @project_image_attachment.save
        format.html { redirect_to @project_image_attachment, notice: 'Project image attachment was successfully created.' }
        format.json { render :show, status: :created, location: @project_image_attachment }
      else
        format.html { render :new }
        format.json { render json: @project_image_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_image_attachments/1
  # PATCH/PUT /project_image_attachments/1.json
  def update
    respond_to do |format|
      if @project_image_attachment.update(project_image_attachment_params)
        format.html { redirect_to @project_image_attachment, notice: 'Project image attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_image_attachment }
      else
        format.html { render :edit }
        format.json { render json: @project_image_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_image_attachments/1
  # DELETE /project_image_attachments/1.json
  def destroy
    @project_image_attachment.destroy
    respond_to do |format|
      format.html { redirect_to project_image_attachments_url, notice: 'Project image attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_image_attachment
      @project_image_attachment = ProjectImageAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_image_attachment_params
      params.require(:project_image_attachment).permit(:project_id, :projectimage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/project_files_helper.rb
module ProjectFilesHelper
end

app/helpers/project_image_attachments_helper.rb
module ProjectImageAttachmentsHelper
end

app/helpers/project_likes_helper.rb
module ProjectLikesHelper
end

app/helpers/project_tag_helper.rb
module ProjectTagHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/user_tag_helper.rb
module UserTagHelper
end

app/views/project_image_attachments/_form.html.erb
<%= form_for(@project_image_attachment) do |f| %>
  <% if @project_image_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_image_attachment.errors.count, "error") %> prohibited this project_image_attachment from being saved:</h2>

      <ul>
      <% @project_image_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :projectimage %><br>
    <%= f.text_field :projectimage %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_image_attachments/edit.html.erb
<h1>Editing project_image_attachment</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_image_attachment %> |
<%= link_to 'Back', project_image_attachments_path %>

app/views/project_image_attachments/index.html.erb
<h1>Listing project_image_attachments</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>Projectimage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_image_attachments.each do |project_image_attachment| %>
      <tr>
        <td><%= project_image_attachment.project_id %></td>
        <td><%= project_image_attachment.projectimage %></td>
        <td><%= link_to 'Show', project_image_attachment %></td>
        <td><%= link_to 'Edit', edit_project_image_attachment_path(project_image_attachment) %></td>
        <td><%= link_to 'Destroy', project_image_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project image attachment', new_project_image_attachment_path %>

app/views/project_image_attachments/new.html.erb
<h1>New project_image_attachment</h1>

<%= render 'form' %>

<%= link_to 'Back', project_image_attachments_path %>

app/views/project_image_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_image_attachment.project_id %>
</p>

<p>
  <strong>Projectimage:</strong>
  <%= @project_image_attachment.projectimage %>
</p>

<%= link_to 'Edit', edit_project_image_attachment_path(@project_image_attachment) %> |
<%= link_to 'Back', project_image_attachments_path %>