config/routes.rb
Rails.application.routes.draw do

  resources :profile, only: [:show] do
    resources :user_tag, only: [:create]
  end

  get 'project_view/new'

  resources :project_files

  resources :project_image_attachments

  resources :projects do
    resources :project_likes, only: [:new]
    resources :project_comments, only: [:create]
    resources :project_tag, only: [:create]
  end

  devise_for :users

  root 'home#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :project_image_attachments, :dependent => :destroy
	has_many :project_files, :dependent => :destroy
	has_many :project_likes, :dependent => :destroy
	has_many :project_views, :dependent => :destroy
	has_many :project_comments, :dependent => :destroy
	has_many :project_tag_maps, :dependent => :destroy
	has_many :project_tags, :through => :project_tag_maps
	accepts_nested_attributes_for :project_image_attachments, :project_files

	after_initialize :set_defaults

	def likeProject user_id
    	if (!likedProject?(user_id))
	    	ProjectLike.create(:project_id => self.id, :user_id => user_id)
	    	self.updateLikes
	    end
	end

	def likedProject? user_id
		self.project_likes.pluck(:user_id).include?(user_id) || self.user_id == user_id
	end

	def viewProject user_id
		if (!viewedProject?(user_id)) # only counting unique views if I identify a user (i.e. if the user is logged in)
			if (user_id)
				ProjectView.create(:project_id => self.id, :user_id => user_id)
				self.updateViews(0)
			else
				# Should I count views where the user is not signed in?
				self.updateViews(1)
			end
		end
		self.views
	end

	def viewedProject? user_id
		if (user_id)
			self.project_views.pluck(:user_id).include?(user_id) || self.user_id == user_id
		else
			false
		end
	end

	def commentedProject? user_id
		if (user_id)
			self.project_comments.pluck(:user_id).include?(user_id) || self.user_id == user_id
		else
			true # You have to be logged in to be able to rate and comment
		end
	end

	def updateScore
		scores = self.project_comments.all.pluck(:score)
		scores.delete(0)
		if (scores.length > 0)
			self.update(:score => scores.sum.to_f / scores.length.to_f)
		end
	end

	def updateLikes
		self.update(:likes => self.project_likes.length)
	end

	def updateViews value
		self.update(:views => self.project_views.length + value)
	end

	private
	def set_defaults
		self.likes ||= 0;
		self.views ||= 0;
		self.score ||= 0;
	end
end

app/models/project_view.rb
class ProjectView < ActiveRecord::Base
	belongs_to :project
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /projects
  # GET /projects.json
  def index
    puts "INDEX!"
    @projects = Project.all
    @user = current_user
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    puts "SHOW"
    
    @projects = Project.find(params[:id])
    @project_image_attachments = @projects.project_image_attachments.all
    @project_files = @projects.project_files.all
    @project_views = @projects.viewProject(current_user.id)
    @project_comments = @project.project_comments
    @project_comment = ProjectComment.new
    @project_tags = @projects.project_tags
    
    @user = current_user
    @project_user = @projects.user
    scores = @project_user.projects_scores
    @project_user_likes = scores[0]
    @project_user_views = scores[1]
    @project_user_score = scores[2]
  end

  # GET /projects/new
  def new
    puts "NEW"
    @project = Project.new
    @project_image_attachments = @project.project_image_attachments.build
    @project_files = @project.project_files.build
  end

  # GET /projects/1/edit
  def edit
    puts "EDIT!"
  end

  # POST /projects
  # POST /projects.json
  def create
    puts "CREATE!"
    p = project_params
    # adding user_id
    p["user_id"] = current_user.id
    puts p
    puts "-----"

    @project = Project.new(p)

    respond_to do |format|
      if @project.save
        params[:project_image_attachments]['projectimage'].each do |a|
            @project_image_attachments = @project.project_image_attachments.create!(:projectimage => a, :project_id => @project.id)
        end
        # This is stupid. For some reason it creates the project files but without the files. No clue why it doesn't do it with Project image attachment...
        desc = @project.project_files.first.description
        # Stupid: Now destroy the project file just created. Also potential race-condition if multiple authors tries to edit the same project files at the same time
        @project.project_files.last.destroy
        pf = @project.project_files
        params[:project_files]['projectfile'].each do |a,index|
            @project_files = @project.project_files.create!(:file => a, :project_id => @project.id, :description => desc)
        end
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    puts "UPDATE!"
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    puts "DESTROY"
    if current_user.id = @project.user_id
      @project.destroy
      respond_to do |format|
        format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to projects_url, alert: "You can't destroy that." }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      puts "SET_PROJECT!"
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      puts "PROJECT_PARAMS!"
      #params.require(:project).permit(:title, :description, :user_id, :likes, :views)
      params.require(:project).permit(:title, :description, :license, project_image_attachments_attributes: [:id, :project_id, :projectimage], project_files_attributes: [:id, :project_id, :projectfile, :description])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="pure-u-1-3">
  <%= form_for @project, url: {action: "create"}, html: {class: "pure-form pure-form-stacked"} do |f| %>
      <fieldset>
          <legend>Create a new project</legend>
           <% if @project.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

                <ul>
                <% @project.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <%= f.text_field :title, :placeholder => "Title" %>

            <%= f.text_area :description, :placeholder => "Description" %>

            <%= f.label :license %>
            <%= f.select :license, options_for_select(["Not sure: Don't copy without permission","GPL: Gnu Public License","CC: Creative Commons","MIT"]) %>

            <%= f.fields_for :project_image_attachments do |p| %>
              <%= p.label :projectimage %>
              <%= p.file_field :projectimage, :multiple => true, name: "project_image_attachments[projectimage][]" %>
            <% end %>

            <%= f.fields_for :project_files do |p| %>
              <%= p.label :projectfile %>
              <%= p.text_area :description, :placeholder => "File description" %>
              <%= p.file_field :projectfile, :multiple => true, name: "project_files[projectfile][]" %>
            <% end %>

            <%= f.submit "Create Project", :class => "pure-button pure-button-primary" %>
      </fieldset>
    <% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container theme-showcase" role="main">
  <div class="browse-main">
    <% @projects.each do |p| %>
      <div class="browse-box">
        <!--div class="browse-title"><%= p.title %></div-->
        <div class="browse-title"><%= link_to p.title, p %></div>
        <div class="browse-author"><%= link_to p.user.username, profile_path(p.user.id) %></div>
        <div class="browse-img">
          <% if p.project_image_attachments %>
            <%= image_tag p.project_image_attachments[0].projectimage.url :thumb %>
          <% end %>
        </div>
        <div class="browse-metric-box">
          <div class="browse-metric"><%= image_tag("thumbsup.png") %><%= p.likes %></div>
          <div class="browse-metric"><%= image_tag("eye.png") %><%= p.views %></div>
          <div class="browse-metric"><%= image_tag("star.png") %><%= p.score %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class="contentwrapper">
	<h1>New project</h1>

	<%= render 'form' %>

</div>

app/views/projects/show.html.erb
<script>
    Galleria.run('.galleria');
</script>
<div class="jumbotron">
  <div id="pv-title">
    <h1><%= @project.title %></h1>
    <div id="pv-subtitle">
      by <strong><%= link_to @project_user.username, projects_path %></strong> 
    </div>
  </div>

  <div id="pv-scores">
    <%= link_to image_tag("thumbsup.png"), new_project_project_like_path(@project.id) %><div id="pv-score"> <%= @project.likes %> </div>
    <%= image_tag("eye.png") %> <div id="pv-score"> <%=  @project_views %> </div>
    <%= image_tag("star.png") %> <div id="pv-score"> <%= @project.score %> </div>
  </div>

  <div id="pv-description">
   <h1>Description:</h1>
   <%= @project.description %>
  </div>

  <div id="pv-userinfo">
    <h1><underline><%= @project_user.username %></underline><h1> <!-- should be username -->
    <div id="pv-userinfo-pic"><%= image_tag @project_user.userimage.url :thumb %></div>
    <div id="pv-userinfo-stat-basic">
      <div class="pv-userinfo-stat-title">#</div><%= @project_user.projects.length %><br/>
      <div class="pv-userinfo-stat-title"> <%= image_tag("thumbsup.png") %></div> <%= @project_user_likes %></br>
      <div class="pv-userinfo-stat-title"> <%= image_tag("eye.png") %></div> <%= @project_user_views %></br>
    </div>
    <div id="pv-userinfo-stat-rating"><%= image_tag("star.png") %> <%= @project_user_score %></div> </br>
    <div id="pv-userinfo-social"><%= image_tag("facebook.png") %><%= image_tag("linkedin.png") %><%= image_tag("twitter.png") %></div>
  </div>

  <div id="pv-media">
    <h1>Media:</h1>
    <% if @project_image_attachments.length > 0 %>
      <div class="galleria">
        <!--img src="/images/facebook.png" data-title="My title" data-description="My description"-->
        <% @project_image_attachments.each do |p| %>
          <%= image_tag p.projectimage_url %>
        <% end %>
      </div>
    <% else %>
      - No media available for this project
    <% end %>
  </div>

  <div id="pv-files">
    <h1>Project files:</h1>
    <% if @project_files.length > 0 %>
      <p><%= @project_files[0].description %></p>
      <ul>
        <% @project_files.each do |p| %>
          <li><%= link_to p.file.file.original_filename, p.file_url %></li>
        <% end %>
      </ul>
    <% else %>
      <p>- No project files available for this project</p>
    <% end %>
  </div>

  <div id="pv-tags">
    <h1>Tags:</h1>
    <div id="pv-tags-content">
      <% @project_tags.each do |u| %>
        <%=u.content%>,
      <% end %>
    </div>
    <% if @project_user.id == @user.id %>
      <%= form_for(:project_tag, url: project_project_tag_index_path(@projects.id)) do |p| %>
        <div class="pv-tags-input">
          <%= p.text_field :content %>
        </div>
        <div class="pv-tags-button">
          <!--<%= p.submit "Add tag" %> -->
          <button type="submit" class="btn btn-sm btn-primary">Add tag</button>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="pv-license">
    <h1>License: </h1> 
    <% if @project.license != nil %>
      <p><%= @project.license %></p>
    <% else %>
      <p>No registered license. Please contact the user for further information before copying.</p>
    <% end %>
  </div>

  <div id="pv-comments">
    <h1>Rate & comments: </h1>
    <p>Do you like/hate this project? Let the builder know how you feel.</p>
    <% if !@project.commentedProject?(@user.id) %>
      <!--%= link_to "Rate & comment", new_project_project_comment_path(@project.id) %-->
      <%= form_for([@project, @project_comment]) do |f| %>
        <% if @project_comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@project_comment.errors.count, "error") %> prohibited this project_comment from being saved:</h2>

            <ul>
            <% @project_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :comment %><br>
          <%= f.text_area :comment %>
        </div>
        <div class="field">
          <%= f.label "Score (0=Don't know, 1=bad, 5=awesome)" %><br>
          <%= f.select :score, options_for_select([0,1,2,3,4,5]) %>
        </div>
        <div class="actions">
          <%= f.submit "Rate & comment" %>
        </div>
      <% end %>
    <% else %>
      <p>You already rated this project or the project is our own.</p>
    <% end %>

    <div id="pv-comments-box">
      <% @project_comments.each do |c| %>
        <div class="pv-1comment">
          <div class="pv-1comment-name"><%= c.user.username %></div>
          <div class="pv-1comment-score">Score: <%= c.score %></div>
          <hr class="pv-1comment-hr"/>
          <div class="pv-1comment-content"><%= c.comment %></div>
        </div>
      <% end %>
    </div>
  </div>

  <!--p>
    <strong>Description:</strong>
    <%= @project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @project.user_id %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= @project.likes %>
  </p>

  <p>
    <strong>Views:</strong>
    <%= @project.views %>
  </p>

  <p>
  <% @project_image_attachments.each do |p| %>
    <%= image_tag p.projectimage_url %>
  <% end %>
  </p-->
</div>