config/routes.rb
Rails.application.routes.draw do

  resources :profile, only: [:show] do
    resources :user_tag, only: [:create]
  end

  get 'project_view/new'

  resources :project_files

  resources :project_image_attachments

  resources :projects do
    resources :project_likes, only: [:new]
    resources :project_comments, only: [:create]
    resources :project_tag, only: [:create]
  end

  devise_for :users

  root 'home#index'

end

app/models/project_file.rb
class ProjectFile < ActiveRecord::Base
  mount_uploader :file, ProjectFileUploader
  belongs_to :project
end

app/controllers/project_files_controller.rb
class ProjectFilesController < ApplicationController
  before_action :set_project_file, only: [:show, :edit, :update, :destroy]

  # GET /project_files
  # GET /project_files.json
  def index
    @project_files = ProjectFile.all
  end

  # GET /project_files/1
  # GET /project_files/1.json
  def show
  end

  # GET /project_files/new
  def new
    @project_file = ProjectFile.new
  end

  # GET /project_files/1/edit
  def edit
  end

  # POST /project_files
  # POST /project_files.json
  def create
    @project_file = ProjectFile.new(project_file_params)

    respond_to do |format|
      if @project_file.save
        format.html { redirect_to @project_file, notice: 'Project file was successfully created.' }
        format.json { render :show, status: :created, location: @project_file }
      else
        format.html { render :new }
        format.json { render json: @project_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_files/1
  # PATCH/PUT /project_files/1.json
  def update
    respond_to do |format|
      if @project_file.update(project_file_params)
        format.html { redirect_to @project_file, notice: 'Project file was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_file }
      else
        format.html { render :edit }
        format.json { render json: @project_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_files/1
  # DELETE /project_files/1.json
  def destroy
    @project_file.destroy
    respond_to do |format|
      format.html { redirect_to project_files_url, notice: 'Project file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_file
      @project_file = ProjectFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_file_params
      params.require(:project_file).permit(:description, :file)
    end
end

app/helpers/project_files_helper.rb
module ProjectFilesHelper
end

app/views/project_files/_form.html.erb
<%= form_for(@project_file) do |f| %>
  <% if @project_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_file.errors.count, "error") %> prohibited this project_file from being saved:</h2>

      <ul>
      <% @project_file.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :file %><br>
    <%= f.text_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_files/edit.html.erb
<h1>Editing project_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @project_file %> |
<%= link_to 'Back', project_files_path %>

app/views/project_files/index.html.erb
<h1>Listing project_files</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>File</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_files.each do |project_file| %>
      <tr>
        <td><%= project_file.description %></td>
        <td><%= project_file.file %></td>
        <td><%= link_to 'Show', project_file %></td>
        <td><%= link_to 'Edit', edit_project_file_path(project_file) %></td>
        <td><%= link_to 'Destroy', project_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project file', new_project_file_path %>

app/views/project_files/new.html.erb
<h1>New project_file</h1>

<%= render 'form' %>

<%= link_to 'Back', project_files_path %>

app/views/project_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @project_file.description %>
</p>

<p>
  <strong>File:</strong>
  <%= @project_file.file %>
</p>

<%= link_to 'Edit', edit_project_file_path(@project_file) %> |
<%= link_to 'Back', project_files_path %>