config/routes.rb
Rails.application.routes.draw do

  resources :profile, only: [:show] do
    resources :user_tag, only: [:create]
  end

  get 'project_view/new'

  resources :project_files

  resources :project_image_attachments

  resources :projects do
    resources :project_likes, only: [:new]
    resources :project_comments, only: [:create]
    resources :project_tag, only: [:create]
  end

  devise_for :users

  root 'home#index'

end

app/models/project_comment.rb
class ProjectComment < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
end

app/controllers/project_comments_controller.rb
class ProjectCommentsController < ApplicationController
  before_action :set_project
  before_action :set_project_comment, only: [:show, :edit, :update, :destroy]

  # GET /project_comments
  # GET /project_comments.json
  def index
    @project_comments = ProjectComment.all
  end

  # GET /project_comments/1
  # GET /project_comments/1.json
  def show
  end

  # GET /project_comments/new
  def new
    @project_comment = @project.project_comments.build#ProjectComment.new
  end

  # GET /project_comments/1/edit
  def edit
  end

  # POST /project_comments
  # POST /project_comments.json
  def create
    puts "COMMENT CREATE"
    puts params
    puts "_---"
    puts project_comment_params

    if !@project.commentedProject?(current_user.id)
      @project_comment = @project.project_comments.build(project_comment_params)#ProjectComment.new(project_comment_params)

      respond_to do |format|
        if @project_comment.save
          @project_comment.update(:user_id => current_user.id) # This is stupid, but right now I don't have a better solution for it
          format.html { redirect_to @project }
          #format.json { render :show, status: :created, location: @project }
        else
          format.html { render :new }
          format.json { render json: @project_comment.errors, status: :unprocessable_entity }
        end
      end
      @project.updateScore
    end
  end

  # PATCH/PUT /project_comments/1
  # PATCH/PUT /project_comments/1.json
  def update
    respond_to do |format|
      if @project_comment.update(project_comment_params)
        format.html { redirect_to @project_comment, notice: 'Project comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_comment }
      else
        format.html { render :edit }
        format.json { render json: @project_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_comments/1
  # DELETE /project_comments/1.json
  def destroy
    @project_comment.destroy
    respond_to do |format|
      format.html { redirect_to project_comments_url, notice: 'Project comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project_comment
      @project_comment = @project.project_comments.find(params[:id])#ProjectComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_comment_params
      params.require(:project_comment).permit(:project_id, :user_id, :comment, :score)
    end
end

app/helpers/project_comments_helper.rb
module ProjectCommentsHelper
end

app/views/project_comments/_form.html.erb
<%= form_for([@project, @project_comment]) do |f| %>
  <% if @project_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project_comment.errors.count, "error") %> prohibited this project_comment from being saved:</h2>

      <ul>
      <% @project_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label "Score (1=bad, 5=awesome)" %><br>
    <%= f.select :score, options_for_select([1,2,3,4,5]) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/project_comments/edit.html.erb
<h1>Editing project_comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@project, @project_comment] %> |
<%= link_to 'Back', project_comments_path(@project) %>

app/views/project_comments/index.html.erb
<h1>Listing project_comments</h1>

<table>
  <thead>
    <tr>
      <th>Project</th>
      <th>User</th>
      <th>Comment</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_comments.each do |project_comment| %>
      <tr>
        <td><%= project_comment.project_id %></td>
        <td><%= project_comment.user_id %></td>
        <td><%= project_comment.comment %></td>
        <td><%= project_comment.score %></td>
        <td><%= link_to 'Show', [@project, @project_comment] %></td>
        <td><%= link_to 'Edit', edit_project_comment_path(@project,project_comment) %></td>
        <td><%= link_to 'Destroy', [@project,project_comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project comment', new_project_comment_path(@project) %>

app/views/project_comments/new.html.erb
<h1>New project_comment</h1>

<%= render 'form' %>

<%= link_to 'Back', project_project_comments_path(@project) %>

app/views/project_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @project_comment.project_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @project_comment.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @project_comment.comment %>
</p>

<p>
  <strong>Score:</strong>
  <%= @project_comment.score %>
</p>

<%= link_to 'Edit', edit_project_comment_path(@project,@project_comment) %> |
<%= link_to 'Back', project_comments_path(@project) %>